### ISSUE TITLE
Introducing rate limiting

### ISSUE THREAD

**Issue by ksysoev** [ksysoev/deriv-api-bff#103]
Wasabi provided easy way to configure rate limits for api requests, I think we can make use of it and provide this feature for our users. We can add rate limit configuration under server section , it could look something like this:
```
server:
  rate_limits:
  general:
    - interval: 1m
      limit: 100
  groups:
    - name: group1
      limits:
        - interval: 1h
          limit: 50
      methods:
        - aggregate
    - name: group2
      limits:
        - interval: 30s
          limit: 5
      methods:
        - chain
```
