### ISSUE TITLE
Map/List processor 

### ISSUE THREAD

**Issue by ksysoev** [ksysoev/deriv-api-bff#120]
idea here to introduce new type of processor that will take an array as input and processor will iterate over provided list and execute sub requests, then responses will be collected into final list, order of responses should be preserved.

```yaml
method: "multi_balance"
params:
    login_ids:
        type: array
        maxContains: 8
        items: 
            type: number

backend:
  - request:
      balance: 1
      login_id: "${item}"
    allow:
      - balance
      - currency
```
