### ISSUE TITLE
Requests dependencies

### ISSUE THREAD

**Issue by ksysoev** [ksysoev/deriv-api-bff#16]
For rendering some pages frontend logic may need to request multiple requests where fields from one response will be input arguments for second.

for now lets support only primitive values like number or string boolean. In future we may consider to implement support for more complex structure 

```yaml
api:
  calls:
    - method: "aggregate"
      params:
        country: 
          type: "string"
      backend:
        - response_body: "website_status"
          allow: 
            - api_call_limits
            - clients_country
          request_template: |
            {
              "website_status": 1,
              "req_id": {{ .ReqID }}
            }
        - response_body: "landing_company"
          depends:
            - "website_status"
          allow: 
            - financial_company
            - gaming_company
          fields_map:
            financial_company: "financial"
            gaming_company: "gaming"
          request_template: |
            {
              "landing_company": "{{ index .Resp "website_status" "clients_country" }}",
              "req_id": {{ .ReqID }}
            }
      
```
