### ISSUE TITLE
Add support for HTTP backend

### ISSUE THREAD

**Issue by ksysoev** [ksysoev/deriv-api-bff#18]
For FE development maybe useful to enrich api responses with static information, the easiest way to support this feature I think is to start supporting HTTP API as additional backends. in this case we can host static json files just on nginx and incorporate results into final response.

configuration may look something like this:

```yaml
server:
  listen: ":8080"
deriv:
  endpoint: "wss://ws.derivws.com/websockets/v3"
api:
  calls:
    - method: "aggregate"
      params:
        country: 
          type: "string"
      backend:
        - type: deriv
          response_body: "website_status"
          allow: 
            - api_call_limits
            - clients_country
          request_template: |
            {
              "website_status": 1,
              "req_id": {{ .ReqID }}
            }
        - type: http
          url_template: "/contracts/{{ index .Params "country" }}",
          method: "GET",
          allow: 
            - cfd
          host: "http://localhost:8081"

```
