### ISSUE TITLE
JSON Templates

### ISSUE THREAD

**Issue by ksysoev** [ksysoev/deriv-api-bff#7]
In current implementation I'm using go text templates and it works just fine. The problem I see with this approach that it gives room for mistakes. I think it'd be better to find some format that provides create structure that will be used as JSON Template... from quick search didn't manage to find some well defined format. But before starting development on this issue is better to make some research first.

ideally we should have some thing like this:

```yaml
server:
  listen: ":8080"
deriv:
  endpoint: "wss://ws.derivws.com/websockets/v3"
api:
  calls:
    - method: "aggregate"
      params:
        country: string
      backend:
        - response_body: "landing_company"
          allow: 
            - financial_company
            - gaming_company
          fields_map:
            financial_company: "financial"
            gaming_company: "gaming"
          request_template: 
            landing_company: "{param.county}"
        - response_body: "website_status"
          allow: 
            - api_call_limits
            - clients_country
          request_template: 
            website_status: 1
```

JSON-T looks nice and flexible for defining placeholders for values, maybe we can inspire some ideas from there https://developers.squarespace.com/what-is-json-t . unfortunately I didn't manage to find implementation on Golang
